name: docsync
description: "A new Flutter project."

publish_to: "none" 

version: 0.1.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  responsive_builder: ^0.7.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  gap: ^3.0.1
  phosphor_flutter: ^2.0.1
  dio: ^5.4.0
  retrofit: ^4.0.3
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  device_preview: ^1.1.0
  riverpod_annotation: ^2.3.3
  freezed_annotation: ^2.4.1
  flutter_secure_storage: ^9.0.0
  flutter_quill: ^9.2.0
  socket_io_client: ^2.0.3+1
  flutter_quill_extensions: ^9.2.0
  lottie: ^2.7.0
  envied: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.5.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/folders.png"
  web:
    generate: true
    image_path: "assets/images/folders.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/folders.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter_gen:
  output: lib/src/core/constants/ 
  line_length: 80 
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/gifs/
    - assets/lotties/